// Generated by scripts/inject_config.py — do not edit by hand.
// Edit app_config.dart.template instead.
class AppConfig {
  AppConfig._();

  static const String apiBaseUrl = 'https://6o98lyizu6.execute-api.ap-southeast-2.amazonaws.com/v1';
  static const String cognitoClientId = '202motbr0g7lb5mblvhb4legek';

  static const String _cognitoBaseUrl = 'https://receipt-scanner-025423.auth.ap-southeast-2.amazoncognito.com';

  static const String cognitoAuthEndpoint = '$_cognitoBaseUrl/oauth2/authorize';
  static const String cognitoTokenEndpoint = '$_cognitoBaseUrl/oauth2/token';
  static const String cognitoEndSessionEndpoint = '$_cognitoBaseUrl/logout';

  static const String redirectUri = 'com.willnash.receiptscanner://callback';
  static const String postLogoutRedirectUri =
      'com.willnash.receiptscanner://logout';

  static const List<String> scopes = ['email', 'openid', 'profile'];

  static const int maxFileSizeBytes = 20 * 1024 * 1024;
  static const int pollIntervalMs = 3000;
  static const int pollMaxAttempts = 60;
}
